from fpdf import FPDF
import tempfile

# The built-in PDF fonts only support Latin-1, so characters like the em dash
# or curly quotes (common in AI-written text) would crash the export.
_REPLACEMENTS = {
    "\u2014": "-", "\u2013": "-", "\u2018": "'", "\u2019": "'",
    "\u201c": '"', "\u201d": '"', "\u2026": "...", "\u2022": "-",
    "\u2192": "->", "\u00a0": " ",
}


def _clean(text):
    text = str(text)
    for bad, good in _REPLACEMENTS.items():
        text = text.replace(bad, good)
    return text.encode("latin-1", "replace").decode("latin-1")


class SafePDF(FPDF):
    """FPDF that cleans any text before drawing it."""

    def cell(self, *args, **kwargs):
        args = list(args)
        if len(args) >= 3:
            args[2] = _clean(args[2])
        return super().cell(*args, **kwargs)

    def multi_cell(self, *args, **kwargs):
        args = list(args)
        if len(args) >= 3:
            args[2] = _clean(args[2])
        return super().multi_cell(*args, **kwargs)


def generate_pdf_report(resume_data, scorecard, scores, role, company):
    pdf = SafePDF()
    pdf.add_page()

    # Header
    pdf.set_fill_color(15, 23, 42)
    pdf.rect(0, 0, 210, 40, 'F')
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_xy(0, 10)
    pdf.cell(210, 10, "InterviewOS — Performance Report", align="C")
    pdf.set_font("Helvetica", "", 11)
    pdf.set_xy(0, 24)
    pdf.cell(210, 10, f"{resume_data['name']}  |  {role}  |  {company}", align="C")

    # Reset colour
    pdf.set_text_color(0, 0, 0)
    pdf.set_xy(15, 50)

    # Overall score
    overall = scorecard['overall_score']
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, f"Overall Score: {overall}/10", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, f"Role: {role}  |  Company: {company}", ln=True)
    pdf.ln(4)

    # Skill breakdown
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 9, "Skill Breakdown", ln=True, fill=True)
    pdf.set_font("Helvetica", "", 11)
    for skill, score in scorecard['skill_scores'].items():
        bar_width = int((score / 10) * 80)
        pdf.set_x(15)
        pdf.cell(90, 7, f"{skill}", ln=False)
        pdf.set_fill_color(59, 130, 246)
        pdf.cell(bar_width, 5, "", fill=True, ln=False)
        pdf.set_fill_color(220, 220, 220)
        pdf.cell(80 - bar_width, 5, "", fill=True, ln=False)
        pdf.cell(15, 5, f" {score}/10", ln=True)
        pdf.ln(1)

    pdf.ln(4)

    # Strengths
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 9, "Strengths", ln=True, fill=True)
    pdf.set_font("Helvetica", "", 11)
    for s in scorecard['strengths']:
        pdf.set_x(15)
        pdf.multi_cell(0, 7, f"+ {s}")
    pdf.ln(3)

    # Weaknesses
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 9, "Areas to Improve", ln=True, fill=True)
    pdf.set_font("Helvetica", "", 11)
    for w in scorecard['weaknesses']:
        pdf.set_x(15)
        pdf.multi_cell(0, 7, f"- {w}")
    pdf.ln(3)

    # Study topics
    if scorecard.get('study_topics'):
        pdf.set_font("Helvetica", "B", 13)
        pdf.set_fill_color(240, 240, 240)
        pdf.cell(0, 9, "Recommended Study Topics", ln=True, fill=True)
        pdf.set_font("Helvetica", "", 11)
        for i, topic in enumerate(scorecard['study_topics'], 1):
            pdf.set_x(15)
            pdf.cell(0, 7, f"{i}. {topic}", ln=True)
        pdf.ln(3)

    # Recommendation
    pdf.set_font("Helvetica", "B", 13)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 9, "Overall Recommendation", ln=True, fill=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_x(15)
    pdf.multi_cell(0, 7, scorecard['recommendation'])

    # Footer
    pdf.set_y(-20)
    pdf.set_font("Helvetica", "I", 9)
    pdf.set_text_color(150, 150, 150)
    pdf.cell(0, 10, "Generated by InterviewOS — Adaptive AI Interview Simulator", align="C")

    # Save to temp file
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    pdf.output(tmp.name)
    return tmp.name